version: '3.7'

services:
  huskybot:
    image: kazwolfe/huskybot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - huskyapp

  postgres:
    image: postgres:12
    restart: always
    env_file: .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - huskyapp

  redis:
    image: bitnami/redis:5.0
    restart: always
    env_file: .env
    volumes:
      - redis-data:/bitnami/redis/data
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - huskyapp

volumes:
  pg-data:
  redis-data:

networks:
  huskyapp:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-huskyapp