version: "3"

services:
  huskybot:
    build:
      context: .
      dockerfile: Dockerfile
    image: huskybot:latest
    env_file: .env
    environment:
      - HUSKYBOT_PLATFORM=compose
    ports:
      - "9339:9339"
    networks:
    - resources
    volumes:
      - ./config:/HuskyBot/config
      - ./logs:/HuskyBot/logs
      - ./custom_plugins:/HuskyBot/plugins/custom/:ro
    restart: on-failure
  db:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "huskybot"
    env_file: .env
    volumes:
    - huskybot_db:/var/lib/postgresql/data
    networks:
    - resources

networks:
  resources:

volumes:
  huskybot_db:
