import datetime
import logging

import discord
from discord.ext import commands
from discord.http import Route

from WolfBot import WolfConfig
from WolfBot import WolfConverters
from WolfBot import WolfUtils
from WolfBot.WolfStatics import *

LOG = logging.getLogger("DakotaBot.Plugin." + __name__)


class Intelligence:
    """
    Intelligence is a plugin focusing on gathering information from Discord.

    It is used to query data about users (or roles/guilds) from guilds. Commands are generally open to execution for
    all users, and only expose information provided by the Discord API, not information generated by the bot or bot
    commands.

    All commands here query their information directly from the Discord API in near realtime.
    """

    def __init__(self, bot):
        self.bot = bot
        self._config = WolfConfig.get_config()
        LOG.info("Loaded plugin!")

    @commands.command(name="guildinfo", aliases=["sinfo", "ginfo"], brief="Get information about the current guild")
    @commands.guild_only()
    async def guild_info(self, ctx: discord.ext.commands.Context):
        """
        Get an information dump for the current guild.

        This command returns basic core information about a guild for reporting purposes.

        The command takes no arguments.
        """

        guild = ctx.guild

        guild_details = discord.Embed(
            title="Guild Information for " + guild.name,
            color=guild.owner.color
        )

        guild_details.set_thumbnail(url=guild.icon_url)
        guild_details.add_field(name="Guild ID", value=guild.id, inline=True)
        guild_details.add_field(name="Owner", value=guild.owner.display_name + "#" + guild.owner.discriminator,
                                inline=True)
        guild_details.add_field(name="Members", value=str(len(guild.members)) + " users", inline=True)
        guild_details.add_field(name="Text Channels", value=str(len(guild.text_channels)) + " channels", inline=True)
        guild_details.add_field(name="Roles", value=str(len(guild.roles)) + " roles", inline=True)
        guild_details.add_field(name="Voice Channels", value=str(len(guild.voice_channels)) + " channels", inline=True)
        guild_details.add_field(name="Created At", value=guild.created_at.strftime(DATETIME_FORMAT), inline=True)
        guild_details.add_field(name="Region", value=guild.region, inline=True)

        if len(guild.features) > 0:
            guild_details.add_field(name="Features", value=", ".join(guild.features))

        await ctx.send(embed=guild_details)

    @commands.command(name="roleinfo", aliases=["rinfo"], brief="Get information about a specified role.")
    @commands.guild_only()
    async def role_info(self, ctx: discord.ext.commands.Context, *, role: discord.Role):
        """
        Get basic information about a specific role in this guild.

        This command requires a single argument - a guild identifier. This can either be the guild's name, the guild ID,
        a ping for the guild, or similar.

        This command does not return sensitive information.
        """

        role_details = discord.Embed(
            title="Role Information for " + role.name,
            color=role.color
        )

        role_details.add_field(name="Role ID", value=role.id, inline=True)

        if role.color.value == 0:
            role_details.add_field(name="Color", value="None", inline=True)
        else:
            role_details.add_field(name="Color", value=str(hex(role.color.value)).replace("0x", "#"), inline=True)

        role_details.add_field(name="Mention Preview", value=role.mention, inline=True)
        role_details.add_field(name="Hoisted", value=role.hoist, inline=True)
        role_details.add_field(name="Managed Role", value=role.managed, inline=True)
        role_details.add_field(name="Mentionable", value=role.mentionable, inline=True)
        role_details.add_field(name="Position", value=role.position, inline=True)
        role_details.add_field(name="Member Count", value=str(len(role.members)), inline=True)

        await ctx.send(embed=role_details)

    @commands.command(name="userinfo", aliases=["uinfo", "memberinfo", "minfo", "whois"],
                      brief="Get information about self or specified user")
    async def user_info(self, ctx: discord.ext.commands.Context, *,
                        member: WolfConverters.OfflineMemberConverter = None):
        """
        Get basic information about a calling user.

        This command takes a single (optional) argument - a member identifier. This may be a User ID, a ping, a
        username, a nickname, etc. If this argument is not specified, the bot will return information about the calling
        user.

        This command does not return sensitive information on users, nor does it return punishment records.
        """

        member = member or ctx.author

        if isinstance(member, discord.User):
            member_details = discord.Embed(
                title="User Information for " + member.name + "#" + member.discriminator,
                color=Colors.INFO,
                description="Currently **not a member of any shared guild!**\nData may be limited."
            )
        elif isinstance(member, discord.Member):
            member_details = discord.Embed(
                title="User Information for " + member.name + "#" + member.discriminator,
                color=member.color,
                description="Currently in **" + str(member.status) + "** mode " + WolfUtils.get_fancy_game_data(member)
            )
        else:
            raise ValueError("Illegal state!")

        roles = []
        if isinstance(member, discord.Member) and ctx.guild is not None:
            for r in member.roles:
                if r.name == "@everyone":
                    continue

                roles.append(r.mention)

            if len(roles) == 0:
                roles.append("None")

        member_details.add_field(name="User ID", value=member.id, inline=True)

        if isinstance(member, discord.Member) and ctx.guild is not None:
            member_details.add_field(name="Display Name", value=member.display_name, inline=True)

        member_details.add_field(name="Joined Discord", value=member.created_at.strftime(DATETIME_FORMAT), inline=True)
        member_details.set_thumbnail(url=member.avatar_url)

        if isinstance(member, discord.Member) and ctx.guild is not None:
            member_details.add_field(name="Joined Guild", value=member.joined_at.strftime(DATETIME_FORMAT), inline=True)
            member_details.add_field(name="Roles", value=", ".join(roles), inline=False)

            member_details.set_footer(text="Member #{} on the guild"
                                      .format(str(sorted(ctx.guild.members,
                                                         key=lambda m: m.joined_at).index(member) + 1)))

        await ctx.send(embed=member_details)

    @commands.command(name="avatar", brief="Get a link/high-resolution version of a user's avatar")
    async def avatar(self, ctx: commands.Context, *, user: WolfConverters.OfflineUserConverter = None):
        """
        Get a high-resolution version of a user's avatar.

        This command will attempt to find and return the largest possible version of a user's avatar that it can, as
        well as the avatar hash.

        This command takes a single (optional) argument - a member identifier. This may be a User ID, a ping, a
        username, a nickname, etc. If this argument is not specified, the bot will return the avatar of the calling
        user.
        """

        user = user or ctx.author

        embed = discord.Embed(
            title="Avatar for {}".format(user),
            color=Colors.INFO
        )

        embed.add_field(name="Avatar ID", value="`{}`".format(user.avatar), inline=False)
        embed.add_field(name="Avatar URL", value="[Open In Browser >]({})".format(user.avatar_url), inline=False)
        embed.set_image(url=user.avatar_url)

        await ctx.send(embed=embed)

    @commands.command(name="msgcount", brief="Get a count of messages in a given context")
    @commands.has_permissions(manage_messages=True)
    async def message_count(self, ctx: commands.Context, context: str, timedelta: WolfConverters.DateDiffConverter):
        """
        Get a count of messages in any given context.

        A context/area is defined as a single channel, the keyword "all", or the keyword "public". If a channel name is
        specified, only that channel will be searched. "all" will attempt to search every channel that exists in the
        guild. "public" will search every channel in the guild that can be seen by the @everyone user.

        Timedelta is a time string formatted in 00d00h00m00s format. This may only be used to search back.

        CAVEATS: It is important to know that this is a *slow* command, because it needs to iterate over every message
        in the search channels in order to successfully operate. Because of this, the "Typing" indicator will display.
        Also note that this command may not return accurate results due to the nature of the search system. It should be
        used for approximation only.

        Example commands:

        /msgcount public 7d   - Get a count of all public messages in the last 7 days
        /msgcount all 2d      - Get a count of all messages in the last two days.
        /msgcount #general 5h - Get a count of all messages in #general within the last 5 hours.
        """

        message_count = 0
        search_channels = []

        logging_channel = self._config.get('specialChannels', {}).get(ChannelKeys.STAFF_LOG.value, None)

        now = datetime.datetime.utcnow()
        search_start = now - timedelta

        async with ctx.typing():
            if context.lower() == "all":
                for channel in ctx.guild.text_channels:
                    if channel.id == logging_channel:
                        continue

                    search_channels.append(channel)

            elif context.lower() == "public":
                if not ctx.guild.default_role.permissions.read_messages:
                    await ctx.send(embed=discord.Embed(
                        title="Intelligence Toolkit Error",
                        description="There do not appear to be any public channels in this guild.",
                        color=Colors.DANGER
                    ))
                    return

                for channel in ctx.guild.text_channels:
                    if channel.overwrites_for(ctx.guild.default_role).read_messages is False:
                        continue

                    search_channels.append(channel)
            else:
                converter = commands.TextChannelConverter()
                search_channels.append(await converter.convert(ctx, context))

            for channel in search_channels:
                if not channel.permissions_for(ctx.me).read_message_history:
                    LOG.info("I don't have permission to get information for channel %s", channel)
                    continue

                LOG.info("Getting history for %s", channel)
                hist = channel.history(limit=None, after=search_start)

                async for _ in hist:
                    message_count += 1

            await ctx.send(embed=discord.Embed(
                title="Message Count Report",
                description="Since **`{} UTC`**, the channel context **`{}`** has seen about **`{}`**"
                            " messages.".format(search_start.strftime(DATETIME_FORMAT), context, message_count),
                color=Colors.INFO
            ))

    @commands.command(name="prunesim", brief="Get a number of users scheduled for pruning")
    @commands.has_permissions(manage_guild=True)
    async def check_prune(self, ctx: commands.Context, days: int = 7):
        """
        Simulate a prune on the server.

        This command will simulate a prune on the server and return a count of members expected to be lost. A member is
        considered for pruning if they have not spoken in the specified number of days *and* they have no roles.

        This command takes a single argument: the days to look through. By default, it will look for 7 days, but any
        value between 1 and 180 will be accepted.
        """

        if days < 1 or days > 180:
            raise commands.BadArgument("The `days` argument must be between 1 and 180.")

        prune_count = await ctx.guild.estimate_pruned_members(days=days)

        if days == 1:
            days = "1 day"
        else:
            days = "{} days".format(days)

        if prune_count == 1:
            prune_count = "1 user"
        else:
            prune_count = "{} users".format(prune_count)

        await ctx.send(embed=discord.Embed(
            title="Simulated Prune Report",
            description="With a simulated cutoff of {}, an estimated **{}** will be pruned from the guild. "
                        "\n\nThis number represents the count of members who have not spoken in the last {}, and "
                        "do not have a role (including self-assigned roles).".format(days, prune_count, days),
            color=Colors.INFO
        ))

    @commands.command(name="usercount", brief="Get a count of users on the guild", aliases=["uc"])
    async def user_count(self, ctx: commands.Context):
        """
        Get a count of users on the guild.

        This is a lighter version of /ginfo. It takes no commands.
        """
        await ctx.send(embed=discord.Embed(
            title="User Count Report",
            description="This guild currently has **{} total users**.".format(len(ctx.guild.members)),
            color=Colors.INFO
        ))

    @commands.command(name="invitespy", brief="Find information about Guild invite", aliases=["invspy"])
    @commands.has_permissions(view_audit_log=True)
    async def invitespy(self, ctx: commands.Context, fragment: str):
        try:
            invite_data = await self.bot.http.request(
                Route('GET', '/invite/{invite_id}?with_counts=true', invite_id=fragment))  # type: dict
            invite_guild = discord.Guild(state=self.bot, data=invite_data['guild'])

            if invite_data.get("inviter") is not None:
                invite_user = discord.User(state=self.bot, data=invite_data["inviter"])
            else:
                invite_user = None
        except discord.NotFound:
            await ctx.send(embed=discord.Embed(
                title="Invitespy Error",
                description="This invite does not appear to exist",
                color=Colors.DANGER
            ))
            return

        embed = discord.Embed(
            description="Information about `{}` for Guild {}".format(fragment, invite_guild.name),
            color=Colors.INFO
        )

        embed.set_thumbnail(url=invite_guild.icon_url)

        if invite_user is not None:
            embed.set_author(
                name="Invite for {} by {}#{}".format(invite_guild.name, invite_user.name, invite_user.discriminator),
                icon_url=invite_user.avatar_url
            )
        else:
            embed.set_author(name="Invite for {}".format(invite_guild.name))

        embed.add_field(name="Invited Guild ID", value=invite_guild.id, inline=True)

        ch_type = {0: "#", 2: "[VC] ", 4: "[CAT] "}
        embed.add_field(name="Invited Channel Name",
                        value=ch_type[invite_data['channel']['type']] + invite_data['channel']['name'],
                        inline=True)

        embed.add_field(name="Invited Guild Creation Date",
                        value=invite_guild.created_at.strftime(DATETIME_FORMAT),
                        inline=True)

        if invite_data.get('approximate_member_count', -1) != -1:
            embed.add_field(name="Invited Guild User Count",
                            value="{} ({} online)".format(invite_data.get('approximate_member_count', -1),
                                                          invite_data.get('approximate_presence_count',
                                                                          -1)))

        if len(invite_guild.features) > 0:
            embed.add_field(name="Guild Features", value=', '.join(invite_guild.features))

        await ctx.send(embed=embed)


def setup(bot: commands.Bot):
    bot.add_cog(Intelligence(bot))
